FrontEnd/MyInvoiceWebApp/MyInvoiceWebApp/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyInvoiceWebApp.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Author { get; set; }
        public string ISBN { get; set; }
        public int Price { get; set; }

    }
}

FrontEnd/MyInvoiceWebApp/MyInvoiceWebApp/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyInvoiceWebApp.Models
{
    public class Customer
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Address { get; set; }
        public string Logo { get; set; }
    }
}

FrontEnd/MyInvoiceWebApp/MyInvoiceWebApp/Models/ErrorViewModel.cs
using System;

namespace MyInvoiceWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FrontEnd/MyInvoiceWebApp/MyInvoiceWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyInvoiceWebApp.Helpers;
using MyInvoiceWebApp.Models;
using Newtonsoft.Json;


namespace MyInvoiceWebApp.Controllers
{
    public class HomeController : Controller
    {
        InvoiceAPI _api = new InvoiceAPI();

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        //public async Task<IActionResult> Index()
        //{
        //    List<Book> book = new List<Book>();

        //    HttpClientHandler clientHandler = new HttpClientHandler();
        //    clientHandler.ServerCertificateCustomValidationCallback = (sender, cert, chain, sslPolicyErrors) => { return true; };

        //    // Pass the handler to httpclient(from you are calling api)
        //    //HttpClient client = new HttpClient(clientHandler);
        //    HttpClient client = new HttpClient();
        //    client = _api.Initial();

        //    HttpResponseMessage res = await client.GetAsync("api/Books");

        //    if (res.IsSuccessStatusCode)
        //    {
        //        var result = res.Content.ReadAsStringAsync().Result;
        //        book = JsonConvert.DeserializeObject<List<Book>>(result);
        //        JsonConvert.DeserializeObject
        //    }

        //    return View(book);
        //}

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FrontEnd/MyInvoiceWebApp/MyInvoiceWebApp/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyInvoiceWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MyInvoiceWebApp.Controllers
{
    public class InvoiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Insert(int? id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert()
        {
            return View();
        }

    }
}

FrontEnd/MyInvoiceWebApp/MyInvoiceWebApp/Views/Home/Index.cshtml
@*@model List<MyInvoiceWebApp.Models.Book>*@

@{
    ViewData["Title"] = "Home Page";
}

<br />
<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Book List</h2>
    </div>
    <div class="col-3 offset-3">
        <a asp-action="Insert" asp-controller="Invoice" class="btn btn-info form-control text-white">
            Add New Bill
        </a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Author</th>
                    <th>ISBN</th>
                    <th></th>
                </tr>
            </thead>
            @*<tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelitem => item.Name)</td>
                        <td>@Html.DisplayFor(modelitem => item.Author)</td>
                        <td>@Html.DisplayFor(modelitem => item.ISBN)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { }) | @Html.ActionLink("Edit", "Details", new { }) | @Html.ActionLink("Edit", "Delete", new { })
                        </td>
                    </tr>
                }
            </tbody>*@
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/bookList.js"></script>
}

FrontEnd/MyInvoiceWebApp/MyInvoiceWebApp/Views/Invoice/Insert.cshtml
@model MyInvoiceWebApp.Models.Book

<br />
<h2 class="text-info">PAID | BILL</h2>
<br />

<div class="border container" style="padding:30px;">
    <p>please find attached your invoice. Thank you for timely payment.</p>
    <form method="post">
        <div class="form-group row">
            <div class="col-md-4">
                <label for="cars">Invoice No</label>
                <input class="form-control" />
            </div>
            <div class="col-md-4">
                <label for="cars">Language</label>
                <select name="cars" id="cars">
                    <option>English (US)</option>
                </select>
            </div>
            <div class="col-md-4">
                <label for="cars">Currency</label>
                <select name="cars" id="cars">
                    <option>United State Dollar - USD</option>
                </select>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-3">
                <label for="cars">From : </label>
                <textarea class="form-control" name="comment" form="usrform">Enter text here...</textarea>
            </div>
            <div class="col-md-3">
                <label for="cars">To : </label>
                <textarea class="form-control" name="comment" form="usrform">Enter text here...</textarea>
            </div>
            <div class="col-md-3">
                <label for="cars">Date : </label>
                <input class="form-control" />
            </div>
            <div class="col-md-3">
                <label for="cars">Invoice Due : </label>
                <select name="cars" id="cars">
                    <option>Immediately</option>
                </select>
            </div>
            <div class="col-md-3">
                <label for="cars">Purchase Order Number : </label>
                <input class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    Create
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

FrontEnd/MyInvoiceWebApp/MyInvoiceWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyInvoiceWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyInvoiceWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyInvoiceWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>